server:
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/bootexample.p12
    key-store-password: af3DF*34afefwefehu

  tomcat:
    max-connections: 100
    # Tomcat thread pool
    threads:
      min: 5
      max: 100

custom:
  tracking:
    thread: false

spring:
  cache:
    cache-names: "manytomany,examples,manytoone,onetomany,onetoone"

  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: false
    # properties:
      # hibernate:
        # format_sql: true
        # dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: testuser
    password: testpassword

    hikari:
      minimum-pool-size: 10
      maximum-pool-size: 100

  threads:
    virtual:
      enabled: true
  task:
    execution:
      pool:
        core-size: 5 # Doesn't have an effect if virtual threads are enabled.
        queue-capacity: 100 # Doesn't have an effect if virtual threads are enabled.
        max-size: 10 # Doesn't have an effect if virtual threads are enabled.
    simple:
      concurrency-limit: 500 # Default unbounded